import '@styles/global.css';

import * as css from './layout.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>
        <div className={css.layout}>{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
